### ISSUE TITLE
FileNotFoundError:  'zh-cn-nocut.wav'

### ISSUE THREAD

**Issue by fengyunzaidushi** [jianchang512/pyvideotrans#142]
运行下面的命令：
`
python cli.py --source_mp4 '/dalle3-tts story to website/story to website/Story to Website with dalle3 and TTS.mp4'  --proxy  http://127.0.0.1:7890/   --voice_role zh-CN-YunxiNeural  --voice_autorate  --whisper_model small
`

```
google translate code=200
Traceback (most recent call last):
  File "/mnt/sda/github/12yue/pyvideotrans/cli.py", line 168, in <module>
    running(config.video['source_mp4'])
  File "/mnt/sda/github/12yue/pyvideotrans/cli.py", line 154, in running
    get_large_audio_transcriptioncli(noextname, mp4ext, showprocess)
  File "/mnt/sda/github/12yue/pyvideotrans/videotrans/util/tools.py", line 689, in get_large_audio_transcriptioncli
    merge_audio_segments(segments, start_times, total_length * 1000, noextname)
  File "/mnt/sda/github/12yue/pyvideotrans/videotrans/util/tools.py", line 334, in merge_audio_segments
    merged_audio.export(f'{config.video["target_dir"]}/{noextname}/{config.video["target_language"]}-nocut.wav',
  File "/opt/miniconda3/envs/py39vidro/lib/python3.9/site-packages/pydub/audio_segment.py", line 867, in export
    out_f, _ = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "/opt/miniconda3/envs/py39vidro/lib/python3.9/site-packages/pydub/utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/dalle3-tts story to website/story to website/_video_out/Story to Website with dalle3 and TTS/zh-cn-nocut.wav'

```
![image](https://github.com/jianchang512/pyvideotrans/assets/53250064/d716ce36-aef3-4252-909a-fa82244a0372)
已经转成中文190多条了，如果再重新运行又要消耗挺长时间。

**Comment by jianchang512** [comment]
请使用 gui界面版，cli 很多个版本没维护了，可能存在不少问题。要使用的话，下载 老版本 https://github.com/jianchang512/pyvideotrans/releases/tag/v0.8.0
