### ISSUE TITLE
how can use professional voice of elevenlabs or cloned voice

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#197]
https://github.com/jianchang512/pyvideotrans/assets/428820/6f68a323-52c0-43e6-bd2c-ee29fefa4689

![SNAG-0243](https://github.com/jianchang512/pyvideotrans/assets/428820/5662f48e-d71a-4970-93d4-9e6ff2bec225)

**Comment by jianchang512** [comment]
After adding to VoiceLabs, delete the elevenlabs.json file in the software directory, and then restart the software

**Comment by johnfelipe** [comment]
https://github.com/jianchang512/pyvideotrans/assets/428820/c150d1f0-7133-48a3-be9e-2bd8bb508b43

i follow your steps but my voices is not listed in your app

**Comment by jianchang512** [comment]
1. update to 0.9982
2. delete elevenlabs.json
3. start software

**Comment by johnfelipe** [comment]
Pls review video about 0.9982, crash app, splash show and not show your app, pls help me

**Comment by johnfelipe** [comment]
![SNAG-0248](https://github.com/jianchang512/pyvideotrans/assets/428820/2168f4ca-1612-4de9-adb4-a4f44a76a6ee)

![SNAG-0249](https://github.com/jianchang512/pyvideotrans/assets/428820/4486dc76-b942-4eda-8b1e-cfceb71dd275)


https://github.com/jianchang512/pyvideotrans/assets/428820/b3021155-3c7a-4c87-ba71-b7ddf87ff2c9

not works

**Comment by johnfelipe** [comment]
![SNAG-0255](https://github.com/jianchang512/pyvideotrans/assets/428820/fe314229-7eb5-4dc5-9cf0-855a828077ce)

	Traceback (most recent call last):
	  File "sp.py", line 8, in <module>
	  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
	  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
	  File "videotrans\mainwin\spwin.py", line 12, in <module>
	  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
	  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
	  File "videotrans\task\get_role_list.py", line 6, in <module>
	  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
	  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
	  File "videotrans\util\tools.py", line 12, in <module>
	  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
	  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
	  File "videotrans\configure\config.py", line 79, in <module>
	FileNotFoundError: [Errno 2] No such file or directory: 'd:/Users/GAMEMAX/Downloads/videotrans-v0.9983\\videotrans/language/es.json'

**Comment by johnfelipe** [comment]
ok i copy en.json to es.json and works

**Comment by johnfelipe** [comment]
https://github.com/jianchang512/pyvideotrans/assets/428820/a4222414-895c-452b-9c39-fbd5ecf8783a

crash when i select my name....

**Comment by jianchang512** [comment]
drap and drop to cmd exec

**Comment by jianchang512** [comment]
hold on

**Comment by johnfelipe** [comment]
is working from spanish to english with my voice:

[SNAG-0024.zip](https://github.com/jianchang512/pyvideotrans/files/14041728/SNAG-0024.zip)

but from english to spanish take a lot of time:

![SNAG-0256](https://github.com/jianchang512/pyvideotrans/assets/428820/8c0df957-76eb-4117-bf89-aa8486bd0df7)

im wait 14 min for this, and not finish, i will post when finish

**Comment by johnfelipe** [comment]
ok works from english to spanish, only srt files is not accurated...

**Comment by jianchang512** [comment]
redownload
