### ISSUE TITLE
运行 python sp.py 报错

### ISSUE THREAD

**Issue by vvvvvx** [jianchang512/pyvideotrans#269]
(venv) Artix:[user]:~/py/pyvideotrans$ python sp.py 
Traceback (most recent call last):
  File "/home/user/go/src/py/pyvideotrans/venv/lib/python3.11/site-packages/torch/__init__.py", line 174, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcufft.so.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/go/src/py/pyvideotrans/sp.py", line 8, in <module>
    from videotrans.mainwin.spwin import MainWindow
  File "/home/user/go/src/py/pyvideotrans/videotrans/mainwin/spwin.py", line 11, in <module>
    from videotrans.task.get_role_list import GetRoleWorker
  File "/home/user/go/src/py/pyvideotrans/videotrans/task/get_role_list.py", line 6, in <module>
    from videotrans.util.tools import set_process, get_edge_rolelist, get_elevenlabs_role, get_clone_role
  File "/home/user/go/src/py/pyvideotrans/videotrans/util/tools.py", line 18, in <module>
    from videotrans.separate import st
  File "/home/user/go/src/py/pyvideotrans/videotrans/separate/st.py", line 11, in <module>
    import torch
  File "/home/user/go/src/py/pyvideotrans/venv/lib/python3.11/site-packages/torch/__init__.py", line 234, in <module>
    _load_global_deps()
  File "/home/user/go/src/py/pyvideotrans/venv/lib/python3.11/site-packages/torch/__init__.py", line 195, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/user/go/src/py/pyvideotrans/venv/lib/python3.11/site-packages/torch/__init__.py", line 160, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/home/user/go/src/py/pyvideotrans', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/home/user/go/src/py/pyvideotrans/venv/lib/python3.11/site-packages']

**Comment by jianchang512** [comment]
https://discuss.cryosparc.com/t/libcufft-so-10-cannot-open-shared-object-file/11203/8
https://forums.developer.nvidia.com/t/libcublas-so-11-file-missing-after-installing-cudnn-successfully-and-libcublas-so-12-being-present/246569/4

cuda cudnn 配置问题。

**Comment by jianchang512** [comment]
linux默认安装的torch是cuda版本，加载中报错环境问题，建议安装配置下cuda

**Comment by vvvvvx** [comment]
安装了cuda,不知道咋配置，报错如下：
(venv) Linux:[user]:~/py/pyvideotrans$ python sp.py 
QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: Windows, Fusion

False
False
cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-hwaccel', 'cuvid', '-hwaccel_output_format', 'nv12', '-extra_hw_frames', '2', '-y', '-i', '/home/user/Sync/繁花/Blossoms.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS.mkv', '-c:v', 'h264_nvenc', '-c:a', 'aac', '/home/user/Sync/繁花/Blossoms.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS.mp4']
cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-hwaccel', 'cuvid', '-hwaccel_output_format', 'nv12', '-extra_hw_frames', '2', '-y', '-i', '/home/user/Sync/繁花/Blossoms.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS.mp4', '-vn', '-c:a', 'copy', '/home/user/Sync/繁花/Blossoms.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS/zh-cn.m4a']
cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-hwaccel', 'cuvid', '-hwaccel_output_format', 'nv12', '-extra_hw_frames', '2', '-y', '-i', '/home/user/Sync/繁花/Blossoms.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS.mp4', '-an', '-c:v', 'h264_nvenc', '/home/user/Sync/繁花/Blossoms.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS/novoice.mp4']
cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-hwaccel', 'cuvid', '-hwaccel_output_format', 'nv12', '-extra_hw_frames', '2', '-y', '-i', '/home/user/Sync/繁花/Blossoms.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS/zh-cn.m4a', '-ac', '1', '-ar', '8000', '-b:a', '128k', '-c:a', 'pcm_s16le', '/home/user/go/src/py/pyvideotrans/tmp/Blossoms.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS/tmp.wav']
bbadasTrue
Could not load library libcudnn_cnn_infer.so.8. Error: libcudnn_cnn_infer.so.8: 无法打开共享目标文件: 没有那个文件或目录
Please make sure libcudnn_cnn_infer.so.8 is in your library path!
已中止

**Comment by jianchang512** [comment]
缺少cudnn，还得安装下
搜索linux安装cudnn

**Comment by vvvvvx** [comment]
安装了cudnn,依然报错如下：

(venv) ThinkPad:[user]:~/go/src/py/pyvideotrans$ python sp.py 
QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: Windows, Fusion
False
cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-vsync', 'vfr', '-hwaccel', 'cuvid', '-hwaccel_output_format', 'nv12', '-extra_hw_frames', '2', '-y', '-i', '/home/user/Videos/pyvideotrans/rename/_video_out/tmine-2023-11-03_11.19.18.mp4/zh-cn.m4a', '-ac', '1', '-ar', '8000', '-b:a', '128k', '-c:a', 'pcm_s16le', '/home/user/go/src/py/pyvideotrans/tmp/tmine-2023-11-03_11.19.18.mp4/tmp.wav']
bbadasTrue
Could not load library libcudnn_cnn_infer.so.8. Error: /usr/lib/libcudnn_cnn_infer.so.8: undefined symbol: _ZN5cudnn14cublasSaxpy_v2EP13cublasContextiPKfS3_iPfi, version libcudnn_ops_infer.so.8
Please make sure libcudnn_cnn_infer.so.8 is in your library path!
已中止

**Comment by jianchang512** [comment]
看报错信息。无法加载cudnn库。配置不正确
需要安装匹配cuda版本的cudnn
或者使用openai模型，不需要cudnn
