### ISSUE TITLE
修改了下源码增加了双语字幕，用pyinstaller 打包成exe 没用

### ISSUE THREAD

**Issue by SheddingNeurology** [jianchang512/pyvideotrans#3]
请问作者有打包的教程吗？
万分感谢

**Comment by SheddingNeurology** [comment]
sp.exe.spec
``` spec
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import copy_metadata

datas = []
datas += copy_metadata('openai-whisper', recursive=True)


a = Analysis(
    ['sp.py'],
    pathex=['C:\\Users\\xxxx\\anaconda3\\envs\\video\\Lib\\site-packages'],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='muti-sub.exe',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)

```

**Comment by jianchang512** [comment]
是怎么不能用，可以成功打包，但是打包后的exe执行中出错？在哪一步出错？
如果是这样的话，重新打包，命令使用 `pyinstaller sp.py` 。不要使用 -w 参数，看看控制台错误。
打包后，先不要执行exe，找到代码环境 /Lib/site-packages/ `edge_playback` `edge_tts` `tensorflow` `whisper` `spleeter` 这5个文件夹，复制到 打包后的目录下 _internal 文件夹中，覆盖。

**Comment by SheddingNeurology** [comment]
运行时候报错 代码可以跑的 打包了就不行
``` log
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
--- Logging error ---
Traceback (most recent call last):
  File "tools.py", line 191, in get_large_audio_transcription
  File "speech_recognition\__init__.py", line 1491, in recognize_whisper
  File "whisper\transcribe.py", line 121, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 104, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\_MEI170282\\whisper\\assets\\mel_filters.npz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1083, in emit
  File "logging\__init__.py", line 927, in format
  File "logging\__init__.py", line 663, in format
  File "logging\__init__.py", line 367, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "sp.py", line 40, in run
  File "sp.py", line 77, in running
  File "tools.py", line 200, in get_large_audio_transcription
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Recognize Error:'
Arguments: ("[Errno 2] No such file or directory: 'C:\\\\Users\\\\xxxxx\\\\AppData\\\\Local\\\\Temp\\\\_MEI170282\\\\whisper\\\\assets\\\\mel_filters.npz'",)
ffmpeg version N-112170-gb61733f61f-20230924 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230924
  libavutil      58. 25.100 / 58. 25.100
  libavcodec     60. 27.100 / 60. 27.100
  libavformat    60. 13.100 / 60. 13.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:/Users/xxxxx/Desktop/demo.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.30.100
  Duration: 00:02:30.47, start: 0.000000, bitrate: 1598 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 1464 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
[in#1 @ 000001d7fe27cd40] Error opening input: Invalid data found when processing input
Error opening input file C:/Users/xxxxx/Desktop/demo.srt.
Error opening input files: Invalid data found when processing input
```

**Comment by jianchang512** [comment]
缺少文件，按我上面说的处理下。

**Comment by SheddingNeurology** [comment]
谢谢，替换后可以了。

之前 pyinstaller 使用了 -F
