### ISSUE TITLE
1.55 issue updated from 1.50 / Unhandled exception in script

### ISSUE THREAD

**Issue by johnfelipe** [jianchang512/pyvideotrans#362]
Traceback (most recent call last):
      File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 35, in <module>
      File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 32, in _pyi_rthook
    FileNotFoundError: Tk data directory "d:\Users\GAMEMAX\Downloads\videotrans\_internal\tk" not found.

![SNAG-0152](https://github.com/jianchang512/pyvideotrans/assets/428820/e57726b2-e7f6-4162-83a1-30816b1a6a7c)

**Comment by jianchang512** [comment]
retry download
