### ISSUE TITLE
9.0

### ISSUE THREAD

**Issue by qudongdong123** [jianchang512/pyvideotrans#45]
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'F:\SPFYRJ\SP-videoTranslate-v0.9.0\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sp.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "box.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "vlc.py", line 220, in <module>
  File "vlc.py", line 180, in find_lib
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll '.\\libvlc.dll'. Most likely this dynlib/dll was not found when the application was frozen.
启动时错误提示！！！无法打开程序！！！

**Comment by qudongdong123** [comment]
![提示](https://github.com/jianchang512/pyvideotrans/assets/127782496/83654d8a-0210-4770-9fc7-8caeeddae32b)
我的笔记本是W10的，我下午试一试T台式电脑W11可不可以

**Comment by qudongdong123** [comment]
解决了，是必须要安装VLC media player就可以运行,前面用的播放器是这款PotPlayer 64 bit。

**Comment by jianchang512** [comment]
已处理，打开前会判断，未安装会提示
