### ISSUE TITLE
2.48 list index out of range

### ISSUE THREAD

**Issue by lin16303** [jianchang512/pyvideotrans#540]
即使用最小得tiny模型也报错，前几个版本正常

**Comment by jianchang512** [comment]
2.49 补丁包 
https://github.com/jianchang512/pyvideotrans/releases/download/v2.48/win-PatchUpdate-2.49.7z

**Comment by lin16303** [comment]
还是报错

2024-09-13 10:56:20,816 - VideoTrans - INFO - 语音识别进度 21
2024-09-13 10:56:20,816 - VideoTrans - INFO - 22
00:01:01,760 --> 00:01:05,900
Second, they do do animal sacrifices for their religion, Voodoo.


2024-09-13 10:56:20,816 - VideoTrans - INFO - 语音识别进度 22
2024-09-13 10:56:20,816 - VideoTrans - INFO - 23
00:01:06,140 --> 00:01:09,900
 They  make  these  animal  sacrifices  to  these  gods  for  different  reasons.


2024-09-13 10:56:20,840 - VideoTrans - ERROR - list index out of range
Traceback (most recent call last):
  File "videotrans\recognition\_base.py", line 67, in run
  File "videotrans\recognition\_openai.py", line 203, in _exec
IndexError: list index out of range
2024-09-13 10:56:20,841 - VideoTrans - ERROR - list index out of range
2024-09-13 10:56:20,866 - VideoTrans - ERROR - list index out of range
Traceback (most recent call last):
  File "videotrans\task\job.py", line 75, in run
  File "videotrans\task\trans_create.py", line 206, in recogn
  File "videotrans\recognition\__init__.py", line 95, in run
  File "videotrans\recognition\_base.py", line 67, in run
  File "videotrans\recognition\_openai.py", line 203, in _exec
IndexError: list index out of range
2024-09-13 10:56:20,866 - VideoTrans - ERROR - 语音识别阶段出错:list index out of range
