### ISSUE TITLE
whisper语音转字幕报错:'Transcription' object has no attribute 'segments'

### ISSUE THREAD

**Issue by by2802196784** [jianchang512/pyvideotrans#541]
**出错信息**
Traceback (most recent call last):
  File "videotrans\task\job.py", line 75, in run
  File "videotrans\task\_speech2text.py", line 69, in recogn
  File "videotrans\recognition\__init__.py", line 105, in run
  File "videotrans\recognition\_base.py", line 67, in run
  File "videotrans\recognition\_openairecognapi.py", line 73, in _exec
  File "pydantic\main.py", line 753, in __getattr__
AttributeError: 'Transcription' object has no attribute 'segments'
2024-09-13 11:33:35,060 - VideoTrans - ERROR - 语音识别阶段出错:'Transcription' object has no attribute 'segments'

**复现步骤**
音视频转文字使用chatgpt api

**操作系统**
 - Windows

**软件左上角版本号数字**
2.45

**Comment by jianchang512** [comment]
是使用的第三方api吗，使用官方的试试

要求返回`verbose_json` 格式，很多第三方中转api并未实现
