### ISSUE TITLE
使用DeepLX提示Exception: 3次重试后失败,无有效返回:response.text='{"error":"Translation failed"}'

### ISSUE THREAD

**Issue by baadtooth** [jianchang512/pyvideotrans#567]
![QQ20241011-104624](https://github.com/user-attachments/assets/c3130023-5ab9-427c-85c9-0d126c068c49)
2.45和之后的新版本都会出现这个情况，之前的版本用deeplx翻译正常

**Comment by baadtooth** [comment]
2024-10-11 11:08:16,519 - VideoTrans - INFO - [DeepLX]返回响应,response.text='{"error":"Translation failed"}'
2024-10-11 11:08:16,519 - VideoTrans - ERROR - 无有效返回:response.text='{"error":"Translation failed"}'
Traceback (most recent call last):
  File "videotrans\translator\_deeplx.py", line 46, in _item_task
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "videotrans\translator\_base.py", line 102, in run
  File "videotrans\translator\_deeplx.py", line 48, in _item_task
Exception: 无有效返回:response.text='{"error":"Translation failed"}'
2024-10-11 11:08:16,520 - VideoTrans - INFO - 第2次出错，10s后重试,
2024-10-11 11:08:26,530 - VideoTrans - INFO - 第3次出错，10s后重试,
2024-10-11 11:08:36,534 - VideoTrans - ERROR - 3次重试后失败,无有效返回:response.text='{"error":"Translation failed"}'
2024-10-11 11:08:36,534 - VideoTrans - ERROR - 3次重试后失败,无有效返回:response.text='{"error":"Translation failed"}'
2024-10-11 11:08:36,557 - VideoTrans - ERROR - 3次重试后失败,无有效返回:response.text='{"error":"Translation failed"}'
Traceback (most recent call last):
  File "videotrans\task\job.py", line 102, in run
  File "videotrans\task\trans_create.py", line 270, in trans
  File "videotrans\translator\__init__.py", line 560, in run
  File "videotrans\translator\_base.py", line 90, in run
Exception: 3次重试后失败,无有效返回:response.text='{"error":"Translation failed"}'
2024-10-11 11:08:36,558 - VideoTrans - ERROR - 翻译字幕阶段出错:3次重试后失败,无有效返回:response.text='{"error":"Translation failed"}'

**Comment by jianchang512** [comment]
deeplx没返回翻译结果，返回失败，{"error":"Translation failed"}

这个基本不适合用来翻译字幕，字幕需要短时间发出很多请求，本地部署deeplx会被deepl很快封ip无法使用

**Comment by baadtooth** [comment]
> deeplx没返回翻译结果，返回失败，{"error":"Translation failed"}
> 
> 这个基本不适合用来翻译字幕，字幕需要短时间发出很多请求，本地部署deeplx会被deepl很快封ip无法使用

用的是腾讯云函数结合DeepLX的方法，同样的API在低版本能正常使用，新版本就不行了

**Comment by jianchang512** [comment]
腾讯云早已修改了，无法再运行deeplx了

**Comment by 1-1-2** [comment]
本地部署deeplx会被deepl很快封ip无法使用，可以考虑使用在线部署的带负载均衡的deeplx接口，具体可以在站内搜。

@jianchang512 佬，在这个接口下再提出一个问题，某些 deelpx 的 API，target_lang 参数不支持特指的语言类型，例如支持"ZH"但不支持 "ZH-HANS"。但是这个被写死在了程序里，为了保持一定的灵活性，是否可以在目标语言中提供一个“自定义”选项。

这是我设想的流程：

```
1. 目标语言：下拉栏选择“自定义”
2. 弹窗“请输入deeplx target_lang 参数，可查阅https://developers.deepl.com/docs/resources/supported-languages”
3. 输入“CN”，点击确定。
4. 界面提示为“自定义[$target_lang]”如“自定义[CN]”
```
