### ISSUE TITLE
配音出错

### ISSUE THREAD

**Issue by open9901** [jianchang512/pyvideotrans#568]
我使用覆盖方式更新的最新版本：v2.77
![image](https://github.com/user-attachments/assets/ad01a7de-f4c5-4be1-a67b-917c90f34334)

系统环境:win10 ltsc
具体错误信息：

2024-10-11 21:54:06,268 - VideoTrans - INFO - audio:403/405
2024-10-11 21:54:06,478 - VideoTrans - INFO - audio:404/405
2024-10-11 21:54:06,697 - VideoTrans - INFO - audio:405/405
2024-10-11 21:54:07,015 - VideoTrans - ERROR - Command '['E:/win-videotrans-2.52/ffmpeg/ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'E:/a/_video_out/20xx/novoice.mp4']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "videotrans\util\tools.py", line 338, in runffprobe
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['E:/win-videotrans-2.52/ffmpeg/ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'E:/a/_video_out/20xx/novoice.mp4']' returned non-zero exit status 1.
2024-10-11 21:54:07,017 - VideoTrans - ERROR - ffprobe error,:Command '['E:/win-videotrans-2.52/ffmpeg/ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'E:/a/_video_out/20xx/novoice.mp4']' returned non-zero exit status 1.{  } ,
2024-10-11 21:54:07,021 - VideoTrans - ERROR - ffprobe error,:Command '['E:/win-videotrans-2.52/ffmpeg/ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'E:/a/_video_out/20xx/novoice.mp4']' returned non-zero exit status 1.{  } ,
Traceback (most recent call last):
  File "videotrans\util\tools.py", line 338, in runffprobe
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['E:/win-videotrans-2.52/ffmpeg/ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'E:/a/_video_out/20xx/novoice.mp4']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "videotrans\task\job.py", line 152, in run
  File "videotrans\task\trans_create.py", line 349, in align
  File "videotrans\task\_rate.py", line 52, in run
  File "videotrans\task\_rate.py", line 134, in _ajust_audio
  File "videotrans\util\tools.py", line 418, in get_video_duration
  File "videotrans\util\tools.py", line 361, in get_video_info
  File "videotrans\util\tools.py", line 353, in runffprobe
Exception: ffprobe error,:Command '['E:/win-videotrans-2.52/ffmpeg/ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'E:/a/_video_out/20xx/novoice.mp4']' returned non-zero exit status 1.{  } ,
2024-10-11 21:54:07,024 - VideoTrans - ERROR - 配音阶段出错:ffprobe error,:Command '['E:/win-videotrans-2.52/ffmpeg/ffprobe.exe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'E:/a/_video_out/202xx/novoice.mp4']' returned non-zero exit status 1.{  } ,
2024-10-11 21:54:25,821 - VideoTrans - INFO - segment_900 instruments done

**Comment by jianchang512** [comment]
重试下，再报错时，不要关闭软件，win+r打开输入cmd，然后执行命令

`E:/win-videotrans-2.52/ffmpeg/ffprobe.exe -v quiet -print_format json -show_format -show_streams E:/a/_video_out/20xx/novoice.mp4`

看看输出的红色报错信息

**Comment by open9901** [comment]
win10+cmd执行:
E:/win-videotrans-2.52/ffmpeg/ffprobe.exe -v quiet -print_format json -show_format -show_streams E:/a/_video_out/20xx/novoice.mp4

没有错误提示：
![1728725616331](https://github.com/user-attachments/assets/86cbf7d1-0d19-4327-b7ed-485f7ee45057)

软件界面-出错任务-点击 弹窗，红色文字为：
![1728725700557](https://github.com/user-attachments/assets/bfb93684-e142-4cc4-a716-a1ebdb992884)

另外：我把大文件，分割为小文件，再翻译 也出错
