### ISSUE TITLE
arch linux cuda support

### ISSUE THREAD

**Issue by solitudealma** [jianchang512/pyvideotrans#570]
**出错信息**
出错时软件界面完整截图，以及提示框或控制台报错信息。

```
2024-10-15 21:29:47,647 - VideoTrans - ERROR - CUDA failed with error initialization error
Traceback (most recent call last):
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/_base.py", line 70, in run
    return self._exec()
           ^^^^^^^^^^^^
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/_overall.py", line 104, in _exec
    raise Exception(self.error)
Exception: CUDA failed with error initialization error
2024-10-15 21:29:47,649 - VideoTrans - ERROR - CUDA failed with error initialization error
2024-10-15 21:29:47,649 - VideoTrans - ERROR - CUDA failed with error initialization error('CUDA failed with error initialization error',)
/home/solitudealma/pyvideotrans/venv/lib/python3.12/site-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
Error calling Python override of QThread::run(): 2024-10-15 21:29:47,682 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/solitudealma/pyvideotrans/videotrans/task/_only_one.py", line 35, in run
    trk.recogn()
  File "/home/solitudealma/pyvideotrans/videotrans/task/trans_create.py", line 214, in recogn
    raw_subtitles = run_recogn(
                    ^^^^^^^^^^^
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/__init__.py", line 161, in run
    return FasterAll(**kwargs).run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/_base.py", line 70, in run
    return self._exec()
           ^^^^^^^^^^^^
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/_overall.py", line 104, in _exec
    raise Exception(self.error)
Exception: CUDA failed with error initialization error
```

![image](https://github.com/user-attachments/assets/1f99703b-8184-4b9c-a181-82ba1ae66ced)

**复现步骤**
1. 使用的哪个功能
2. faster模式/openai模式？
3. 使用的模型名

![image](https://github.com/user-attachments/assets/989931f0-a9f8-4e83-9899-90888608a98e)

**操作系统**
 - Windows/Linux/MacOS

**软件左上角版本号数字**

**Comment by solitudealma** [comment]
安装 dbus-python后还是一样
```
2024-10-15 21:57:34,313 - VideoTrans - ERROR - CUDA failed with error initialization error
Traceback (most recent call last):
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/_base.py", line 70, in run
    return self._exec()
           ^^^^^^^^^^^^
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/_overall.py", line 104, in _exec
    raise Exception(self.error)
Exception: CUDA failed with error initialization error
2024-10-15 21:57:34,314 - VideoTrans - ERROR - CUDA failed with error initialization error
2024-10-15 21:57:34,314 - VideoTrans - ERROR - CUDA failed with error initialization error('CUDA failed with error initialization error',)
Error calling Python override of QThread::run(): 2024-10-15 21:57:34,328 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/solitudealma/pyvideotrans/videotrans/task/_only_one.py", line 35, in run
    trk.recogn()
  File "/home/solitudealma/pyvideotrans/videotrans/task/trans_create.py", line 214, in recogn
    raw_subtitles = run_recogn(
                    ^^^^^^^^^^^
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/__init__.py", line 161, in run
    return FasterAll(**kwargs).run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/_base.py", line 70, in run
    return self._exec()
           ^^^^^^^^^^^^
  File "/home/solitudealma/pyvideotrans/videotrans/recognition/_overall.py", line 104, in _exec
    raise Exception(self.error)
Exception: CUDA failed with error initialization error
```

**Comment by elcerilla** [comment]
same problem
