### ISSUE TITLE
配音出错2

### ISSUE THREAD

**Issue by open9901** [jianchang512/pyvideotrans#576]
我使用覆盖方式更新的最新版本：v2.82
![1729267094949](https://github.com/user-attachments/assets/2fcfc2f2-a04d-45c1-9087-4b2cf6086d45)
系统环境:win10 ltsc
具体错误信息：

2024-10-18 23:51:02,062 - VideoTrans - INFO - 配音阶段 [80/86]
2024-10-18 23:51:03,270 - VideoTrans - INFO - 配音阶段 [85/86]
2024-10-18 23:51:03,935 - VideoTrans - INFO - 配音阶段 [86/86]
2024-10-18 23:51:03,974 - VideoTrans - ERROR - 配音出错数量大于1/3，请检查:
2024-10-18 23:51:03,974 - VideoTrans - ERROR - 配音出错数量大于1/3，请检查:
2024-10-18 23:51:03,976 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "videotrans\task\_only_one.py", line 91, in run
  File "videotrans\task\trans_create.py", line 317, in dubbing
  File "videotrans\task\trans_create.py", line 535, in _tts
  File "videotrans\tts\__init__.py", line 141, in run
  File "videotrans\tts\_base.py", line 113, in run
Exception: 配音出错数量大于1/3，请检查:

**Comment by open9901** [comment]
补充：
刚才截图的版本是2.79的，
我现在用2.82 更新后，又操作一次，出现同样错误：
![1729271598902](https://github.com/user-attachments/assets/b658c3d5-0f04-44f0-814d-ecff8002b81a)


2024-10-19 00:22:18,092 - VideoTrans - INFO - 配音阶段 [85/98]
2024-10-19 00:22:18,720 - VideoTrans - INFO - 配音阶段 [90/98]
2024-10-19 00:22:19,621 - VideoTrans - INFO - 配音阶段 [95/98]
2024-10-19 00:22:20,673 - VideoTrans - INFO - 配音阶段 [98/98]
2024-10-19 00:22:20,733 - VideoTrans - ERROR - 配音出错数量大于1/3，请检查:
2024-10-19 00:22:20,733 - VideoTrans - ERROR - 配音出错数量大于1/3，请检查:
2024-10-19 00:22:21,273 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "videotrans\task\_only_one.py", line 87, in run
  File "videotrans\task\trans_create.py", line 375, in dubbing
  File "videotrans\task\trans_create.py", line 605, in _tts
  File "videotrans\tts\__init__.py", line 141, in run
  File "videotrans\tts\_base.py", line 114, in run
Exception: 配音出错数量大于1/3，请检查:

**Comment by jianchang512** [comment]
上代理

**Comment by open9901** [comment]
已解决
多谢！

**Comment by jiaochenglong** [comment]
很奇怪，昨天还可以用，今天就不行了，和代理没关系，我能上GitHub的

**Comment by jiaochenglong** [comment]
> 已解决 多谢！

啊？怎么解决的，我也是相同问题 1/3
