### ISSUE TITLE
语音识别进度 中断:IndexError: string index out of range

### ISSUE THREAD

**Issue by open9901** [jianchang512/pyvideotrans#577]
我使用覆盖方式更新的最新版本：v2.83
![1729318631857](https://github.com/user-attachments/assets/cc330874-382a-44f9-afd0-012d73b13f31)
系统环境:win10 ltsc
具体错误信息：

2024-10-19 13:29:27,961 - VideoTrans - INFO - 语音识别进度 50
2024-10-19 13:29:27,963 - VideoTrans - INFO - 50
00:07:03,320 --> 00:07:03,800
Basically.

2024-10-19 13:29:28,077 - VideoTrans - ERROR - string index out of range
Traceback (most recent call last):
  File "videotrans\recognition\_base.py", line 70, in run
  File "videotrans\recognition\_openai.py", line 86, in _exec
  File "videotrans\recognition\_base.py", line 196, in re_segment_sentences
  File "videotrans\util\tools.py", line 1319, in cleartext
IndexError: string index out of range
2024-10-19 13:29:28,081 - VideoTrans - ERROR - string index out of range
2024-10-19 13:29:28,082 - VideoTrans - ERROR - string index out of range('string index out of range',)
2024-10-19 13:29:28,084 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "videotrans\task\_only_one.py", line 33, in run
  File "videotrans\task\trans_create.py", line 269, in recogn
  File "videotrans\recognition\__init__.py", line 136, in run
  File "videotrans\recognition\_base.py", line 70, in run
  File "videotrans\recognition\_openai.py", line 86, in _exec
  File "videotrans\recognition\_base.py", line 196, in re_segment_sentences
  File "videotrans\util\tools.py", line 1319, in cleartext
IndexError: string index out of range

已挂代理

**Comment by open9901** [comment]
方法就是：将文件分割为小文件，然后翻译，如果还是出错，继续分割，直到正常，
一般只有单个文件很大会出错
