### ISSUE TITLE
3.33 returned non-zero exit status 4294967294.

### ISSUE THREAD

**Issue by lin16303** [jianchang512/pyvideotrans#659]
特定视频，f5clone或固定音色都报错
2024-12-07 13:40:13,471 - VideoTrans - INFO - force_cpu=False,cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/0d74964113/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:04.240', '-ar', '16000', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache/0-4240-1733550013.471511-0.wav']
2024-12-07 13:40:13,693 - VideoTrans - ERROR - cmd执行出错抛出异常force_cpu=False:cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/0d74964113/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:04.240', '-ar', '16000', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache/0-4240-1733550013.471511-0.wav'],[aist#0:0/pcm_s16le @ 00000181635992c0] Guessed Channel Layout: stereo
Input #0, wav, from 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/0d74964113/vocal.wav':
  Duration: 00:02:33.57, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
[out#0/wav @ 0000018163599480] Error opening output C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache/0-4240-1733550013.471511-0.wav: No such file or directory
Error opening output file C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache/0-4240-1733550013.471511-0.wav.
Error opening output files: No such file or directory
Traceback (most recent call last):
  File "videotrans\util\tools.py", line 523, in runffmpeg
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/0d74964113/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:04.240', '-ar', '16000', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache/0-4240-1733550013.471511-0.wav']' returned non-zero exit status 4294967294.
2024-12-07 13:40:13,694 - VideoTrans - ERROR - Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/0d74964113/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:04.240', '-ar', '16000', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache/0-4240-1733550013.471511-0.wav']' returned non-zero exit status 4294967294.
2024-12-07 13:40:13,715 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "videotrans\task\_only_one.py", line 89, in run
  File "videotrans\task\trans_create.py", line 422, in dubbing
  File "videotrans\task\trans_create.py", line 657, in _tts
  File "videotrans\util\tools.py", line 1301, in cut_from_audio
  File "videotrans\util\tools.py", line 523, in runffmpeg
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/0d74964113/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:04.240', '-ar', '16000', 'C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache/0-4240-1733550013.471511-0.wav']' returned non-zero exit status 4294967294.

**Comment by jianchang512** [comment]
看看是否存在这个目录
`C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache`
换用edgetts试试是否正常

**Comment by lin16303** [comment]
另视频慢速gpu不起作用，cpu全部拉满

**Comment by lin16303** [comment]
> 看看是否存在这个目录 `C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache` 换用edgetts试试是否正常

因为是特定视频，其他视频暂时无法复现

**Comment by lin16303** [comment]
> 看看是否存在这个目录 `C:/Users/Alex/Downloads/win-videotrans-v3.33/tmp/dubbing_cache` 换用edgetts试试是否正常

2024-12-08 21:57:18,960 - VideoTrans - INFO - 连接音频片段:2039/2039
2024-12-08 21:57:19,694 - VideoTrans - INFO - force_cpu=False,cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/target.wav', '-c:a', 'aac', '-ar', '48000', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/target.m4a']
2024-12-08 21:59:00,062 - VideoTrans - ERROR - Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/novoice.mp4']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "videotrans\util\tools.py", line 568, in runffprobe
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/novoice.mp4']' returned non-zero exit status 1.
2024-12-08 21:59:00,063 - VideoTrans - ERROR - ffprobe error cmd=['-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/novoice.mp4'] :Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/novoice.mp4']' returned non-zero exit status 1.{  } ,
2024-12-08 21:59:01,131 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "videotrans\util\tools.py", line 568, in runffprobe
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/novoice.mp4']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "videotrans\task\_only_one.py", line 91, in run
  File "videotrans\task\trans_create.py", line 464, in align
  File "videotrans\util\tools.py", line 663, in get_video_duration
  File "videotrans\util\tools.py", line 604, in get_video_info
  File "videotrans\util\tools.py", line 583, in runffprobe
Exception: ffprobe error cmd=['-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/novoice.mp4'] :Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', 'D:/gpt4all/win-videotrans-v3.33/tmp/8eb4c40df2/novoice.mp4']' returned non-zero exit status 1.{  } ,
