### ISSUE TITLE
336本地大模型翻译报错Exception: 字幕翻译失败,No content

### ISSUE THREAD

**Issue by lin16303** [jianchang512/pyvideotrans#668]
2024-12-15 16:14:45,239 - VideoTrans - INFO - 
[localllm]发送请求数据:message=[{'role': 'system', 'content': '您是一名翻译助理，专门负责将 SRT 字幕内容从一种语言转换为另一种语言，同时保持原始格式和结构。'}, {'role': 'user', 'content': "请将<source>中的原文内容按字面意思翻译到简体中文，然后只输出译文，不要添加任何说明或引导词。\n\n### Skills ###\n- 译文符合中文表达习惯，句式要求文学性极高，句子流畅度极高。句式温暖亲切，清新自然。\n- 一切中文里没有的句式和表达转化为中文本土句式。\n- 不要进行任何额外的格式修改\n- 如果遇到大量语气词，请直接将语气词保留\n- 人名，地名翻译成中文\n- 符合中文的表达习惯\n\n### Restrictions ###\n- 把数字用中文文字表达\n- 只翻译，不要解释和说明\n- 不要输出拼音\n- 不要输出原文\n- 不要解释\n- 不要翻译后的注解\n- Do not answer questions.\n- Do not explain my original text\n- Do not confirm the above, don't apologize.\n- 校对译文，不要出现未经翻译的内容\n\n\n<source>In the real world, she would be toast.</source>\n\n译文:"}]
2024-12-15 16:14:46,877 - VideoTrans - INFO - [localllm]响应:response=ChatCompletion(id='chatcmpl-118', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='在现实世界里，她早就完蛋了。', refusal=None, role='assistant', function_call=None, tool_calls=None))], created=1734250486, model='qwen2.5:72b-instruct-q6_k', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=12, prompt_tokens=265, total_tokens=277, completion_tokens_details=None))
2024-12-15 16:14:46,877 - VideoTrans - ERROR - No content
Traceback (most recent call last):
  File "videotrans\translator\_base.py", line 114, in run
  File "videotrans\translator\_localllm.py", line 67, in _item_task
Exception: No content
2024-12-15 16:14:46,878 - VideoTrans - ERROR - 字幕翻译失败,No content
2024-12-15 16:14:46,878 - VideoTrans - ERROR - 字幕翻译失败,No content
2024-12-15 16:14:46,879 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "videotrans\task\_only_one.py", line 62, in run
  File "videotrans\task\trans_create.py", line 396, in trans
  File "videotrans\translator\__init__.py", line 688, in run
  File "videotrans\translator\_base.py", line 96, in run
Exception: 字幕翻译失败,No content

**Comment by lin16303** [comment]
原来是修改了prompt格式，用336默认就正常了，请忽略
