### ISSUE TITLE
3.38 f5clone配音报错

### ISSUE THREAD

**Issue by lin16303** [jianchang512/pyvideotrans#675]
2024-12-17 21:21:35,231 - VideoTrans - INFO - force_cpu=False,cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'E:/AI/win-videotrans-v3.38/tmp/e48a87a227/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:03.960', '-ar', '16000', 'E:/AI/win-videotrans-v3.38/tmp/dubbing_cache/0-3960-1734441695.231775-0.wav']
2024-12-17 21:21:35,445 - VideoTrans - ERROR - cmd执行出错抛出异常force_cpu=False:cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'E:/AI/win-videotrans-v3.38/tmp/e48a87a227/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:03.960', '-ar', '16000', 'E:/AI/win-videotrans-v3.38/tmp/dubbing_cache/0-3960-1734441695.231775-0.wav'],[aist#0:0/pcm_s16le @ 000001a33c315b40] Guessed Channel Layout: stereo
Input #0, wav, from 'E:/AI/win-videotrans-v3.38/tmp/e48a87a227/vocal.wav':
  Duration: 00:02:48.90, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
[out#0/wav @ 000001a33c315400] Error opening output E:/AI/win-videotrans-v3.38/tmp/dubbing_cache/0-3960-1734441695.231775-0.wav: No such file or directory
Error opening output file E:/AI/win-videotrans-v3.38/tmp/dubbing_cache/0-3960-1734441695.231775-0.wav.
Error opening output files: No such file or directory
Traceback (most recent call last):
  File "videotrans\util\tools.py", line 522, in runffmpeg
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'E:/AI/win-videotrans-v3.38/tmp/e48a87a227/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:03.960', '-ar', '16000', 'E:/AI/win-videotrans-v3.38/tmp/dubbing_cache/0-3960-1734441695.231775-0.wav']' returned non-zero exit status 4294967294.
2024-12-17 21:21:35,446 - VideoTrans - ERROR - Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'E:/AI/win-videotrans-v3.38/tmp/e48a87a227/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:03.960', '-ar', '16000', 'E:/AI/win-videotrans-v3.38/tmp/dubbing_cache/0-3960-1734441695.231775-0.wav']' returned non-zero exit status 4294967294.
2024-12-17 21:21:35,457 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "videotrans\task\_only_one.py", line 89, in run
  File "videotrans\task\trans_create.py", line 461, in dubbing
  File "videotrans\task\trans_create.py", line 696, in _tts
  File "videotrans\util\tools.py", line 1298, in cut_from_audio
  File "videotrans\util\tools.py", line 522, in runffmpeg
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'E:/AI/win-videotrans-v3.38/tmp/e48a87a227/vocal.wav', '-ss', '00:00:00.000', '-to', '00:00:03.960', '-ar', '16000', 'E:/AI/win-videotrans-v3.38/tmp/dubbing_cache/0-3960-1734441695.231775-0.wav']' returned non-zero exit status 4294967294.

**Comment by jianchang512** [comment]
看看是不是 f5-tts配音中出错了，f5终端应有显示错误

**Comment by lin16303** [comment]
不是每个视频都报错，但同样视频3.33，3.36正常
