### ISSUE TITLE
OpenAl在线api语音识别使用第三方时报错"'TranscriptionSegment' object is not subscriptable"

### ISSUE THREAD

**Issue by xwxYa** [jianchang512/pyvideotrans#687]
**出错信息**
![image](https://github.com/user-attachments/assets/a2db3e6d-22a9-4d79-be46-bb5ec6b27a7c)
![image](https://github.com/user-attachments/assets/ac0d781d-5107-4874-a68b-af9625dd3dad)
`Traceback (most recent call last):
  File "videotrans\recognition\_base.py", line 73, in run
  File "videotrans\recognition\_openairecognapi.py", line 82, in _exec
TypeError: 'TranscriptionSegment' object is not subscriptable
2024-12-23 18:45:22,903 - VideoTrans - ERROR - 'TranscriptionSegment' object is not subscriptable`

**复现步骤**
1. 使用**OpenAl在线api语音识别**功能
2. 填写第三方API URL与SK
3. 使用模型whisper-1
(已确认该api可用并且有whisper-1模型)

**操作系统**
 - Windows11

**使用版本**
v3.41

**Comment by jianchang512** [comment]
第三方api不支持返回带时间戳的格式，无法制作字幕，请使用openai官方

**Comment by gsessylu** [comment]
按照教程https://pyvideotrans.com/groq，使用groq也出现TranscriptionSegment' object is not subscriptable
