### ISSUE TITLE
3.39-3.42 IndexError: list index out of range, 用3.06正常

### ISSUE THREAD

**Issue by lin16303** [jianchang512/pyvideotrans#697]
2024-12-29 21:32:06,281 - VideoTrans - INFO - force_cpu=False,cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'C:/Users/Alex/Downloads/win-videotrans-v3.42-tiny/tmp/a40803c996/vocal.wav', '-ss', '00:42:57.203', '-to', '00:43:02.373', '-ar', '16000', 'C:/Users/Alex/Downloads/win-videotrans-v3.42-tiny/tmp/dubbing_cache/2577203-2582373-1735479126.2815373-512.wav']
2024-12-29 21:32:08,078 - VideoTrans - INFO - force_cpu=False,cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'C:/Users/Alex/Downloads/win-videotrans-v3.42-tiny/tmp/a40803c996/vocal.wav', '-ss', '00:43:32.322', '-to', '00:43:36.367', '-ar', '16000', 'C:/Users/Alex/Downloads/win-videotrans-v3.42-tiny/tmp/dubbing_cache/2612322-2616367-1735479128.0789971-513.wav']
2024-12-29 21:32:09,887 - VideoTrans - INFO - force_cpu=False,cmd=['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-i', 'C:/Users/Alex/Downloads/win-videotrans-v3.42-tiny/tmp/a40803c996/vocal.wav', '-ss', '00:43:40.955', '-to', '00:43:41.789', '-ar', '16000', 'C:/Users/Alex/Downloads/win-videotrans-v3.42-tiny/tmp/dubbing_cache/2620955-2621789-1735479129.8875742-514.wav']
2024-12-29 21:32:11,706 - VideoTrans - ERROR - list index out of range
2024-12-29 21:32:12,270 - VideoTrans - ERROR - Uncaught exception
Traceback (most recent call last):
  File "videotrans\task\_only_one.py", line 89, in run
  File "videotrans\task\trans_create.py", line 461, in dubbing
  File "videotrans\task\trans_create.py", line 676, in _tts
IndexError: list index out of range

**Comment by lin16303** [comment]
同一段视频3.33也正常
