### ISSUE TITLE
mac使用的时候报错

### ISSUE THREAD

**Issue by xm318bk** [jianchang512/pyvideotrans#86]
Traceback (most recent call last):
  File "/Users/lzl/Desktop/ai翻译/pyvideotrans/videotrans/task/main_worker.py", line 47, in run
    runffmpeg([
  File "/Users/lzl/Desktop/ai翻译/pyvideotrans/videotrans/util/tools.py", line 321, in runffmpeg
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, creationflags=subprocess.CREATE_NO_WINDOW)
AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW'
zsh: abort      /usr/local/bin/python3 sp.py

**Comment by jianchang512** [comment]
拉取最新的源码

**Comment by jianchang512** [comment]
或者将 /Users/lzl/Desktop/ai翻译/pyvideotrans/videotrans/util/tools.py 文件中321行附近
creationflags=subprocess.CREATE_NO_WINDOW
这几个字符删掉

**Comment by xm318bk** [comment]
好的谢谢成功了
