### ISSUE TITLE
批量转换视频，第二个视频会找不到音频文件

### ISSUE THREAD

**Issue by SkywalkerJi** [jianchang512/pyvideotrans#89]
命令行报错
```
Traceback (most recent call last):
  File "C:\Users\test\Videos\pyvideotrans\pyvideotrans\videotrans\task\main_worker.py", line 73, in run
    self.split_wav_novicemp4()
  File "C:\Users\test\Videos\pyvideotrans\pyvideotrans\videotrans\task\main_worker.py", line 68, in split_wav_novicemp4
    shutil.copy(self.a_name,f"{config.video['target_dir']}/{self.noextname}/{config.video['source_language']}.wav")
  File "C:\Users\test\miniconda3\Lib\shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\test\miniconda3\Lib\shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'e:/pickpak/_video_out/g-13/ja.wav'
```

报错之后看了下pyvideotrans目录下temp里有g-13.wav和novoice.mp4，但视频目录_video_out下没有g-13文件夹。

**Comment by jianchang512** [comment]
等下次修复

**Comment by jianchang512** [comment]
更新 应该可以了
